# Config file for automatic testing at travis-ci.org

language: python
matrix:
    include:
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
        - python: pypy
          dist: trusty
          sudo: false
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis
  - pip install -U tox-venv

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ilovetux
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: ilovetux/aina
    python: 3.6
